// This file was automatically generated by the Soy compiler.
// Please don't edit this file by hand.
// source: sources/clo/greeter.soy

/**
 * @fileoverview Templates in namespace io.bazel.rules.closure.soy.greeter.
 * @public
 */

goog.provide('io.bazel.rules.closure.soy.greeter');

goog.require('goog.soy');
goog.require('soy');
goog.require('soy.asserts');
goog.require('soydata.VERY_UNSAFE');


/**
 * @param {!io.bazel.rules.closure.soy.greeter.greet.Params} opt_data
 * @param {(?goog.soy.IjData|?Object<string, *>)=} opt_ijData
 * @return {!goog.soy.data.SanitizedHtml}
 * @suppress {checkTypes}
 */
io.bazel.rules.closure.soy.greeter.greet = function(opt_data, opt_ijData) {
  opt_ijData = /** @type {!goog.soy.IjData} */ (opt_ijData);
  /** @type {string} */
  const name = soy.asserts.assertType(typeof opt_data.name === 'string', 'name', opt_data.name, 'string');
  return soydata.VERY_UNSAFE.ordainSanitizedHtml('<p' + (goog.DEBUG && soy.$$debugSoyTemplateInfo ? ' data-debug-soy="io.bazel.rules.closure.soy.greeter.greet sources/clo/greeter.soy:9"' : '') + '>Hello <b>' + soy.$$escapeHtml(name) + '</b>!');
};
/**
 * @typedef {{
 *  name: string,
 * }}
 */
io.bazel.rules.closure.soy.greeter.greet.Params;
if (goog.DEBUG) {
  /** @type {string} */
  io.bazel.rules.closure.soy.greeter.greet.soyTemplateName = 'io.bazel.rules.closure.soy.greeter.greet';
}
